version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5440:5432"
