version: '3'

services:
  postgres:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT}:5432"
  redis:
    image: redis:4.0.11-alpine
    ports:
      - "${REDIS_PORT}:6379"
