version: '3'

# docker-compose always reads from .env there's no way to explicitly set this
# file to something else so we cannot make use of the values from .test.env we
# have to hardcode the values here
services:
  postgres_test:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_DB: "go_auth_test"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5441:5432"
  redis_test:
    image: redis:4.0.11-alpine
    ports:
      - "6381:6379"
