version: '3'

services:
  postgres_test:
    image: postgres:9.6
    env_file: ".test.env"
    environment:
      POSTGRES_DB: "${POSTGRESDB}"
      POSTGRES_PASSWORD: "${POSTGRESPASSWORD}"
      POSTGRES_USER: "${POSTGRESUSER}"
    ports:
      - "${POSTGRESPORT}:5432"
